import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body className="antialiased">
        <header className="site-header">
          <div className="site-header-left">
            <Image width={70} height={70} className="object-contain" src="/hcl.png" alt="HCL" />
            <h1 className="site-header-title">
              高光谱定标与学习实验室
            </h1>
          </div>
          <div className="text-slate-600 font-medium">
            软件包
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
